/*
 * tokenizer.c — BPE tokenizer with TOKBIN loading.
 *
 * Loads vocabulary and merge table from .tokbin binary format
 * (generated by export_tokenizer.py from HuggingFace tokenizer.json).
 *
 * Implements:
 *   - Byte-level BPE encoding (GPT-2 algorithm)
 *   - Detokenization via vocabulary lookup
 *   - FIM (Fill-in-the-Middle) tokenization
 *   - Canonical special token IDs (matching Python tokenizer exactly)
 *
 * ds4: pure C, zero external deps. Single .tokbin file for all data.
 */
#include "tinyllm.h"
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* ── TOKBIN binary format constants ──────────────────────────────── */
#define TOKBIN_MAGIC  0x424B4F54  /* "TOKB" LE */
#define TOKBIN_VERSION 2

/* ── FNV-1a hash for merge table ─────────────────────────────────── */
#define FNV_OFFSET 2166136261u
#define FNV_PRIME  16777619u

static uint32_t fnv_hash_u32(uint32_t a, uint32_t b) {
    uint32_t h = FNV_OFFSET;
    h ^= (uint8_t)(a);       h *= FNV_PRIME;
    h ^= (uint8_t)(a >> 8);  h *= FNV_PRIME;
    h ^= (uint8_t)(b);       h *= FNV_PRIME;
    h ^= (uint8_t)(b >> 8);  h *= FNV_PRIME;
    return h;
}

/* ── Merge hash table ────────────────────────────────────────────── */
/* Uses uint64_t key: (a << 32) | b for unambiguous pair lookup */
#define MERGE_TABLE_BITS 18
#define MERGE_TABLE_SIZE (1 << MERGE_TABLE_BITS)
#define MERGE_KEY(a,b)   ((((uint64_t)(uint32_t)(a)) << 32) | ((uint64_t)(uint32_t)(b)))

static int merge_table_find(const tl_tokenizer_t *t, tl_token_t a, tl_token_t b) {
    uint64_t key = MERGE_KEY(a, b);
    uint32_t idx = fnv_hash_u32((uint32_t)a, (uint32_t)b) & (MERGE_TABLE_SIZE - 1);
    for (int i = 0; i < 128; i++) {
        uint32_t probe = (idx + (uint32_t)i) & (MERGE_TABLE_SIZE - 1);
        /* Check if slot is empty (rank == -1 signals empty) */
        if (t->merges[probe].key == 0 && t->merges[probe].rank == -1)
            return -1;
        if (t->merges[probe].key == key)
            return t->merges[probe].rank;
    }
    return -1;
}

static void merge_table_insert(tl_tokenizer_t *t, tl_token_t a, tl_token_t b, int rank) {
    uint64_t key = MERGE_KEY(a, b);
    uint32_t idx = fnv_hash_u32((uint32_t)a, (uint32_t)b) & (MERGE_TABLE_SIZE - 1);
    for (int i = 0; i < 128; i++) {
        uint32_t probe = (idx + (uint32_t)i) & (MERGE_TABLE_SIZE - 1);
        if (t->merges[probe].key == 0 || t->merges[probe].key == key) {
            t->merges[probe].key  = key;
            t->merges[probe].rank = rank;
            return;
        }
    }
}

/* ── Trie for reverse lookup (raw bytes → token ID) ───────────────── */
static void trie_insert(tl_tokenizer_t *t, const uint8_t *bytes, int len, int token_id) {
    struct tl_trie_node *node = t->trie_root;
    for (int i = 0; i < len; i++) {
        uint8_t b = bytes[i];
        if (!node->children[b])
            node->children[b] = tl_calloc(1, sizeof(struct tl_trie_node));
        node = node->children[b];
    }
    node->token_id = token_id;
}

static int trie_find_longest(const tl_tokenizer_t *t, const uint8_t *bytes, int len,
                             int *out_token_id, int *out_match_len) {
    struct tl_trie_node *node = t->trie_root;
    int best_id  = -1;
    int best_len = 0;
    for (int i = 0; i < len; i++) {
        uint8_t b = bytes[i];
        if (!node->children[b]) break;
        node = node->children[b];
        if (node->token_id >= 0) {
            best_id  = node->token_id;
            best_len = i + 1;
        }
    }
    if (best_id >= 0) {
        *out_token_id  = best_id;
        *out_match_len = best_len;
        return 1;
    }
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════
   TOKBIN Loader
   ═══════════════════════════════════════════════════════════════════ */

static int read_u32_le(FILE *fp, uint32_t *out) {
    uint8_t buf[4];
    if (fread(buf, 1, 4, fp) != 4) return -1;
    *out = (uint32_t)buf[0] | ((uint32_t)buf[1] << 8) |
           ((uint32_t)buf[2] << 16) | ((uint32_t)buf[3] << 24);
    return 0;
}

static int read_u16_le(FILE *fp, uint16_t *out) {
    uint8_t buf[2];
    if (fread(buf, 1, 2, fp) != 2) return -1;
    *out = (uint16_t)buf[0] | ((uint16_t)buf[1] << 8);
    return 0;
}

tl_tokenizer_t *tl_tokenizer_load(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "⚠️  Cannot open tokenizer file: %s\n", path);
        fprintf(stderr, "   Generate with: python export_tokenizer.py\n");
        return NULL;
    }

    uint32_t magic, version, vocab_size, n_merges, n_specials, max_token_bytes, flags;
    if (read_u32_le(fp, &magic) || magic != TOKBIN_MAGIC) {
        fprintf(stderr, "❌ Bad .tokbin magic: 0x%08X\n", magic);
        fclose(fp); return NULL;
    }
    if (read_u32_le(fp, &version) || version != TOKBIN_VERSION) {
        fprintf(stderr, "❌ Bad .tokbin version: %d\n", version);
        fclose(fp); return NULL;
    }
    read_u32_le(fp, &vocab_size);
    read_u32_le(fp, &n_merges);
    read_u32_le(fp, &n_specials);
    read_u32_le(fp, &max_token_bytes);
    read_u32_le(fp, &flags);

    printf("📥 Loading tokenizer: %s\n", path);
    printf("   vocab=%d, merges=%d, specials=%d\n", vocab_size, n_merges, n_specials);

    tl_tokenizer_t *t = tl_calloc(1, sizeof(tl_tokenizer_t));
    t->vocab_size = (int)vocab_size;
    t->n_merges   = (int)n_merges;
    t->vocab      = tl_calloc(vocab_size, sizeof(char*));

    /* ── Read special token IDs ──────────────────────────────── */
    uint32_t sids[32];
    int ns = (int)(n_specials < 32 ? n_specials : 32);
    for (int i = 0; i < ns; i++) {
        if (read_u32_le(fp, &sids[i])) goto fail;
    }
    t->bos_id   = (tl_token_t)(ns > 0 ? sids[0] : 0);
    t->eos_id   = (tl_token_t)(ns > 1 ? sids[1] : 1);
    t->pad_id   = (tl_token_t)(ns > 2 ? sids[2] : 2);
    t->unk_id   = (tl_token_t)(ns > 3 ? sids[3] : 3);
    t->fim_prefix_id = (tl_token_t)(ns > 4 ? sids[4] : 4);
    t->fim_suffix_id = (tl_token_t)(ns > 5 ? sids[5] : 5);
    t->fim_middle_id = (tl_token_t)(ns > 6 ? sids[6] : 6);

    printf("   IDs: BOS=%d EOS=%d PAD=%d UNK=%d FIM=(%d,%d,%d)\n",
           t->bos_id, t->eos_id, t->pad_id, t->unk_id,
           t->fim_prefix_id, t->fim_suffix_id, t->fim_middle_id);

    /* ── Read vocabulary ─────────────────────────────────────── */
    uint8_t *rbuf = tl_alloc(max_token_bytes + 4);
    for (uint32_t i = 0; i < vocab_size; i++) {
        uint16_t blen;
        if (read_u16_le(fp, &blen)) goto fail;
        if (blen == 0) { uint16_t pad; read_u16_le(fp, &pad); continue; }
        if (blen > max_token_bytes + 4) goto fail;
        if (fread(rbuf, 1, blen, fp) != blen) goto fail;
        t->vocab[i] = tl_alloc(blen + 1);
        memcpy(t->vocab[i], rbuf, blen);
        t->vocab[i][blen] = '\0';
        int total = 2 + (int)blen;
        int pad = (4 - total % 4) % 4;
        if (pad) fseek(fp, pad, SEEK_CUR);
    }
    tl_free(rbuf);

    /* ── Build trie ──────────────────────────────────────────── */
    t->trie_root = tl_calloc(1, sizeof(struct tl_trie_node));
    for (int i = 0; i < (int)vocab_size; i++) {
        if (t->vocab[i])
            trie_insert(t, (const uint8_t*)t->vocab[i], (int)strlen(t->vocab[i]), i);
    }

    /* ── Read merges ─────────────────────────────────────────── */
    t->merge_capacity = MERGE_TABLE_SIZE;
    t->merges = tl_calloc(MERGE_TABLE_SIZE, sizeof(t->merges[0]));
    for (int i = 0; i < MERGE_TABLE_SIZE; i++)
        t->merges[i].rank = -1;

    for (uint32_t i = 0; i < n_merges; i++) {
        uint32_t a, b, rank;
        if (read_u32_le(fp, &a) || read_u32_le(fp, &b) || read_u32_le(fp, &rank)) goto fail;
        merge_table_insert(t, (tl_token_t)a, (tl_token_t)b, (int)rank);
    }

    fclose(fp);
    printf("✅ Tokenizer ready: %d vocab, %d merges\n", t->vocab_size, t->n_merges);
    return t;

fail:
    fclose(fp);
    tl_tokenizer_free(t);
    return NULL;
}

/* ═══════════════════════════════════════════════════════════════════
   BPE Encoding (GPT-2 byte-level algorithm)
   ═══════════════════════════════════════════════════════════════════ */

int tl_tokenize(tl_tokenizer_t *t, const char *text, tl_token_t *tokens, int max_tokens) {
    if (!t || !text || !tokens || max_tokens <= 0) return 0;

    int text_len = (int)strlen(text);
    if (text_len == 0) return 0;

    /* Step 1: UTF-8 bytes → initial token IDs via longest-trie-match */
    int cap = text_len * 3 + 256;
    tl_token_t *ids = tl_alloc((size_t)cap * sizeof(tl_token_t));
    int n_ids = 0;
    const uint8_t *bytes = (const uint8_t*)text;
    int pos = 0;

    while (pos < text_len && n_ids < cap - 4) {
        int mid, mlen;
        if (trie_find_longest(t, bytes + pos, text_len - pos, &mid, &mlen)) {
            ids[n_ids++] = (tl_token_t)mid;
            pos += mlen;
        } else {
            /* Fallback: byte token = NUM_SPECIALS + byte_value */
            ids[n_ids++] = (tl_token_t)(bytes[pos]) + TL_NUM_SPECIAL_TOKENS;
            pos++;
        }
    }

    /* Step 2: Iterative BPE merging — always merge lowest-rank pair first */
    int max_iter = n_ids * 3;
    for (int iter = 0; iter < max_iter; iter++) {
        int best_i = -1, best_rank = 0x7FFFFFFF;
        for (int i = 0; i < n_ids - 1; i++) {
            int r = merge_table_find(t, ids[i], ids[i+1]);
            if (r >= 0 && r < best_rank) { best_rank = r; best_i = i; }
        }
        if (best_i < 0) break;
        /* Merged token ID = NUM_SPECIALS + 256 + rank */
        tl_token_t merged = (tl_token_t)(TL_NUM_SPECIAL_TOKENS + 256 + best_rank);
        if (merged >= (tl_token_t)t->vocab_size)
            merged = (tl_token_t)(t->vocab_size - 1);
        ids[best_i] = merged;
        if (best_i + 2 < n_ids)
            memmove(ids + best_i + 1, ids + best_i + 2,
                    (size_t)(n_ids - best_i - 2) * sizeof(tl_token_t));
        n_ids--;
    }

    int result = (n_ids < max_tokens) ? n_ids : max_tokens;
    if (tokens) memcpy(tokens, ids, (size_t)result * sizeof(tl_token_t));
    tl_free(ids);
    return result;
}

/* ── FIM tokenization ─────────────────────────────────────────────── */
int tl_tokenize_fim(tl_tokenizer_t *t, const char *prefix, const char *suffix,
                    tl_token_t *tokens, int max_tokens) {
    int n = 0;
    if (n < max_tokens) tokens[n++] = t->fim_prefix_id;
    n += tl_tokenize(t, prefix, tokens ? tokens + n : NULL,
                     max_tokens > 0 ? max_tokens - n : 0);
    if (n < max_tokens) tokens[n++] = t->fim_suffix_id;
    n += tl_tokenize(t, suffix, tokens ? tokens + n : NULL,
                     max_tokens > 0 ? max_tokens - n : 0);
    if (n < max_tokens) tokens[n++] = t->fim_middle_id;
    return n;
}

/* ── Detokenization ───────────────────────────────────────────────── */
char *tl_detokenize(tl_tokenizer_t *t, const tl_token_t *tokens, int n_tokens) {
    size_t est = (size_t)n_tokens * 16 + 1;
    char *out = tl_alloc(est);
    size_t pos = 0;
    for (int i = 0; i < n_tokens; i++) {
        tl_token_t tok = tokens[i];
        if (tok == t->bos_id || tok == t->eos_id || tok == t->pad_id ||
            tok == t->fim_prefix_id || tok == t->fim_suffix_id || tok == t->fim_middle_id)
            continue;
        if (tok >= 0 && tok < t->vocab_size && t->vocab[tok]) {
            int len = (int)strlen(t->vocab[tok]);
            while (pos + (size_t)len + 1 > est) {
                est *= 2;
                char *nw = realloc(out, est);
                if (!nw) { tl_free(out); return NULL; }
                out = nw;
            }
            memcpy(out + pos, t->vocab[tok], (size_t)len);
            pos += (size_t)len;
        }
    }
    out[pos] = '\0';
    return out;
}

/* ── Trie free ────────────────────────────────────────────────────── */
static void trie_free_node(struct tl_trie_node *node) {
    if (!node) return;
    for (int i = 0; i < 256; i++) trie_free_node(node->children[i]);
    tl_free(node);
}

void tl_tokenizer_free(tl_tokenizer_t *t) {
    if (!t) return;
    tl_free(t->merges);
    if (t->vocab) {
        for (int i = 0; i < t->vocab_size; i++) tl_free(t->vocab[i]);
        tl_free(t->vocab);
    }
    trie_free_node(t->trie_root);
    tl_free(t->encode_cache);
    tl_free(t);
}
